version: '3.9'

services:
    postgresql:
        container_name: void-postgres
        image: docker.io/bitnami/postgresql:latest
        volumes:
        - postgresql_data:/bitnami/postgresql
        ports:
        - 5437:5432
        environment:
        - POSTGRESQL_USERNAME=void
        - POSTGRESQL_PASSWORD=postgres
        - POSTGRESQL_DATABASE=void
        networks:
            - void-network

networks:
    void-network:
        driver: bridge

volumes:
    postgresql_data:
        driver: local
